apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-web
  description: "quarkusdroneshop-web のWebフロントエンドサービスです"
  tags:
    - latest
    - a-cluster
  labels:
    app: web
  annotations:
    backstage.io/kubernetes-id: quarkusdroneshop-web
    backstage.io/kubernetes-cluster: a-cluster
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=quarkusdroneshop-web
    argocd/app-selector: app.kubernetes.io/instance=quarkusdroneshop-web
    tektonci.io/pipeline: build-and-push-quarkusdroneshop-web
    tektonci.io/pipelineNamespace: quarkusdroneshop-cicd
    tekton.dev/type: pipeline
    tekton.dev/cicd: "true"
    janus-idp.io/tekton: "true"
    rhdh.redhat.com/tekton-enabled: "true"
    backstage.io/techdocs-ref: dir:.
spec:
  type: web
  lifecycle: production
  owner: user:default/nmushino
  system: a-cluster
  dependsOn:
    - resource:shop-cluster-kafka
    - resource:shop-orders-in
  providesApis:
    - kafka-orders-in
  consumesApis:
    - kafka-web-updates
    - kafka-loyalty-updates
