apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-web
  annotations:
    github.com/project-slug: quarkusdroneshop/quarkusdroneshop-web
spec:
  type: other
  lifecycle: unknown
  owner: admin
