apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-web
  description: Webサービス用のマイクロサービスです
  labels:
    app: web
  annotations:
    github.com/project-slug: quarkusdroneshop/web
    backstage.io/kubernetes-label-selector: 'app=web'
    backstage.io/kubernetes-namespace: quarkusdroneshop-demo
    backstage.io/kubernetes-cluster: a-cluster
spec:
  type: service
  owner: user:default/nmushino
  lifecycle: production
  system: a-cluster
  providesApis:
    - quarkusdroneshop-web-api
  kubernetes:
    serviceLocatorMethod: 'multiTenant'
    auth:
      defaultAuthType: serviceAccount
    clusters:
      - name: a-cluster
        skipTLSVerify: true
        authProvider: serviceAccount
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: quarkusdroneshop-web-api
  description: オーダ情報API
spec:
  type: openapi
  lifecycle: production
  owner: user:default/nmushino
  definition: |
    openapi: 3.0.0
    info:
      title: quarkusdroneshop-web API
      version: 5.2.0
    paths:
      /order:
        get:
          summary: オーダ情報を取得
          responses:
            '200':
              description: OK