apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkusdroneshop-web
  description: Webサービス用のマイクロサービスです
  labels:
    app: web
  annotations:
    github.com/project-slug: quarkusdroneshop/web
spec:
  type: website
  owner: user:default/nmushino
  lifecycle: production